[package]
name = "crudcrate"
version = "0.1.4"
edition = "2021"
description = "Rust traits and functions to aid in building CRUD APIs in Axum and Sea-ORM"
license = "MIT"
readme = "README.md"
repository = "https://github.com/evanjt/crudcrate"
keywords = ["crud", "api", "axum", "sea-orm"]
categories = ["web-programming", "database"]

[dependencies]
async-trait = "0.1"
sea-orm = "1.1.6"
uuid = { version = "1.15.1", features = ["serde", "v4"] }
serde = { version = "1.0.218", features = ["derive"] }
utoipa = "5.3.1"
axum = "0.8.1"
hyper = "1.6.0"
serde_json = "1.0.139"
crudcrate-derive = "0.1.3"

[lib]
proc-macro = false

[workspace]
