[package]
name = "crudcrate"
version = "0.4.0"
edition = "2024"
description = "Rust traits and functions to aid in building CRUD APIs in Axum and Sea-ORM"
license = "MIT"
readme = "README.md"
repository = "https://github.com/evanjt/crudcrate"
keywords = ["crud", "api", "axum", "sea-orm"]
categories = ["web-programming", "database"]

[dependencies]
async-trait = "0.1.88"
sea-orm = "1.1.13"
uuid = { version = "1.17.0", features = ["serde", "v4"] }
serde = { version = "1.0.219", features = ["derive"] }
utoipa = "5.4.0"
axum = { version = "0.8.4", features = ["macros"] }
hyper = "1.6.0"
serde_json = "1.0.140"
serde_with = "3.14.0"
crudcrate-derive = "0.2.0"

[lib]
proc-macro = false

[lints.clippy]
pedantic = "warn"
