[package]
name = "crudcrate"
version = "0.1.4"
edition = "2021"
description = "Rust traits and functions to aid in building CRUD APIs in Axum and Sea-ORM"
license = "MIT"
readme = "README.md"
repository = "https://github.com/evanjt/crudcrate"
keywords = ["crud", "api", "axum", "sea-orm"]
categories = ["web-programming", "database"]

[dependencies]
async-trait = "0.1.87"
sea-orm = "1.1.7"
uuid = { version = "1.15.1", features = ["serde", "v4"] }
serde = { version = "1.0.218", features = ["derive"] }
utoipa = "5.3.1"
axum = { version = "0.8.1", features = ["macros"] }
hyper = "1.6.0"
serde_json = "1.0.140"
crudcrate-derive = "0.1.3"
# aide = { version = "0.14.1", features = ["axum", "axum-extra-cookie", "axum-extra-cookie-private", "axum-extra-form", "axum-extra-headers", "axum-extra-json-deserializer", "axum-extra-query", "axum-form", "axum-json", "axum-matched-path", "axum-multipart", "axum-original-uri", "axum-query", "axum-tokio", "axum-ws", "macros", "scalar"] }
# schemars = "0.8.22"
# crudcrate-derive = { path = "../crudcrate-derive/" }

[lib]
proc-macro = false

[workspace]

[lints.clippy]
pedantic = "warn"
